# Generated by Django 3.2 on 2022-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('notify_mode', models.IntegerField(choices=[(1, '邮件'), (2, '钉钉'), (3, '企业微信')], default=1, verbose_name='通知方式')),
                ('email_recipient', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮件收件人')),
                ('dingding_webhook', models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉Webhook')),
                ('weixin_webhook', models.CharField(blank=True, max_length=100, null=True, verbose_name='企业微信Webhook')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '通知管理',
                'db_table': 'system_config_notify',
                'ordering': ('-id',),
            },
        ),
    ]
