# Generated by Django 3.2 on 2022-07-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_release', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseconfig',
            name='notify',
        ),
        migrations.AddField(
            model_name='releaseconfig',
            name='notify_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='消息通知'),
        ),
        migrations.AlterField(
            model_name='releaseconfig',
            name='git_credential_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='凭据ID'),
        ),
    ]
