# Generated by Django 3.2 on 2022-07-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_release', '0002_auto_20220724_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseapply',
            name='version_id',
        ),
    ]
