# Generated by Django 3.2 on 2022-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_release', '0003_remove_releaseapply_version_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseconfig',
            name='exclude_files',
        ),
        migrations.AddField(
            model_name='releaseconfig',
            name='source_file',
            field=models.TextField(blank=True, default='*', null=True, verbose_name='源文件'),
        ),
    ]
