# Generated by Django 3.2 on 2022-07-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_release', '0004_auto_20220724_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('env_id', models.IntegerField(verbose_name='环境ID')),
                ('app_id', models.IntegerField(verbose_name='应用ID')),
                ('title', models.CharField(max_length=30, verbose_name='发布标题')),
                ('version_id', models.CharField(max_length=100, unique=True, verbose_name='版本标识')),
                ('server_ids', models.JSONField(verbose_name='目标主机')),
                ('post_rollback_script', models.TextField(blank=True, null=True, verbose_name='回滚后执行脚本')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('release_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '历史版本',
                'db_table': 'app_release_history_version',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='releaseapply',
            name='deploy_result',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='部署结果'),
        ),
    ]
